{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nude-detector.serviceAccountName" . }}
  labels:
    {{- include "nude-detector.labels" . | nindent 4 }}
{{- end }} 