name: Create and publish a Docker image

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha
          flavor: |
            latest=${{ steps.extract_branch.outputs.branch == 'master' }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install/upgrade helm chart to Kubernetes cluster
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
        run: |
          helm3 upgrade nsfw-detector ./deploy/nude-detector \
            --wait \
            --install \
            --namespace nude-detector \
            --create-namespace \
            --set image.name=${{ steps.meta.outputs.tags }} \
            --timeout 5m0s \
            --debug
